# Generated by Django 4.0.3 on 2022-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aabasoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('shift_time', models.CharField(max_length=100)),
            ],
        ),
    ]
